# Generated by Django 4.1.1 on 2022-09-29 06:52

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetail',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Provide a number with country code (e.g. +12125552368).', max_length=128, null=True, region=None, verbose_name='Phone no.'),
        ),
        migrations.AlterField(
            model_name='products',
            name='lmitate',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Provide a number with country code (e.g. +12125552368).', max_length=128, null=True, region=None, verbose_name='Phone no.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Provide a number with country code (e.g. +12125552368).', max_length=128, null=True, region=None, verbose_name='Phone no.'),
        ),
    ]
