# Generated by Django 4.1.1 on 2022-10-13 11:25

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0003_businesscustomers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                help_text="Provide a number with country code (e.g. +12125552368).",
                max_length=128,
                region=None,
                unique=True,
                verbose_name="Phone no.",
            ),
        ),
    ]
