# Generated by Django 4.1.1 on 2022-10-19 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_seller_alter_businesscustomers_updated_by_and_more'),
        ('seller', '0005_seller_alter_products_options_and_more'),
    ]

    operations = [
    ]
