# Generated by Django 3.2.13 on 2022-10-19 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_alter_seller_options'),
        ('seller', '0006_merge_20221019_0955'),
    ]

    operations = [
    ]
