# Generated by Django 4.1.1 on 2022-12-03 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_merge_20221019_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetail',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='staff_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='is_business_staff',
            field=models.BooleanField(default=False),
        ),
    ]
