# Generated by Django 4.1.1 on 2022-12-03 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_orderproduct_lmitate'),
        ('seller', '0007_merge_20221019_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_id', to='order.order'),
        ),
    ]
