# Generated by Django 4.1.1 on 2022-12-05 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_businessdetail_staff_user_is_business_staff'),
        ('seller', '0008_notifications_order'),
    ]

    operations = [
    ]
