# Generated by Django 4.1.1 on 2022-12-16 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0009_merge_20221205_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscustomers',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_id', to='seller.notifications'),
        ),
    ]
