# Generated by Django 4.1.1 on 2022-12-23 09:05

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0010_businesscustomers_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[("SELLER", "SELLER"), ("BUYER", "BUYER")], max_length=10
            ),
        ),
    ]
