# Generated by Django 4.1.1 on 2023-01-02 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0015_alter_businesscustomers_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="seller.businessdetail",
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promotions",
                to="seller.businessdetail",
            ),
        ),
    ]
