# Generated by Django 4.1.1 on 2023-01-12 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0010_alter_order_business_alter_order_created_by_and_more"),
        ("seller", "0016_alter_products_business_alter_promotion_business"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesscustomers",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="business_customers",
                to="seller.businessdetail",
            ),
        ),
        migrations.AlterField(
            model_name="businesscustomers",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="business_customers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="businesscustomers",
            name="notification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="business_customers",
                to="seller.notifications",
            ),
        ),
        migrations.AlterField(
            model_name="businessdetail",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="business_details",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="businessdetail",
            name="staff",
            field=models.ManyToManyField(
                blank=True,
                related_name="staff_business_details",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collections",
                to="seller.businessdetail",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="products",
            field=models.ManyToManyField(
                related_name="collections", to="seller.products"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="seller.businessdetail",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="customer",
            field=models.ManyToManyField(
                related_name="group_customers", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="order.order",
            ),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receiver_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sender_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promotions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="group",
            field=models.ManyToManyField(related_name="promotions", to="seller.group"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="product",
            field=models.ManyToManyField(
                related_name="promotions", to="seller.products"
            ),
        ),
    ]
