# Generated by Django 4.1.1 on 2023-01-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0017_alter_businesscustomers_business_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotion",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
