# Generated by Django 4.1.1 on 2023-02-28 10:32

import backend.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0019_user_business_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessdetail",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to="media",
                validators=[backend.utils.validate_file_size],
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to="media",
                validators=[backend.utils.validate_file_size],
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="seller.products",
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to="media",
                validators=[backend.utils.validate_file_size],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media",
                validators=[backend.utils.validate_file_size],
            ),
        ),
    ]
