# Generated by Django 4.1.1 on 2023-02-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0020_alter_businessdetail_image_alter_productimage_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="unit",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
