# Generated by Django 4.1.1 on 2023-03-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0024_myfcmdevice"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessdetail",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
