# Generated by Django 4.1.1 on 2023-04-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0025_businessdetail_is_deleted_user_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="status",
            field=models.CharField(
                choices=[(1, "Active"), (2, "Out of stock"), (3, "Discontinued")],
                default=1,
                max_length=20,
            ),
        ),
    ]
