# Generated by Django 4.1.1 on 2022-10-03 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_alter_businessdetail_phone_number_and_more'),
        ('buyer', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='total_amount',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='cart',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_business', to='seller.businessdetail'),
        ),
    ]
