# Generated by Django 4.1.1 on 2022-10-16 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import seller.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seller', '0005_seller_alter_businesscustomers_updated_by_and_more'),
        ('buyer', '0003_rename_total_amount_cart_amount_cart_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('seller.user',),
            managers=[
                ('objects', seller.models.BaseManager()),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
