# Generated by Django 4.1.1 on 2022-10-19 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_buyer_alter_cart_amount_alter_cart_business_and_more'),
        ('buyer', '0004_buyer_alter_cart_updated_by'),
    ]

    operations = [
    ]
