# Generated by Django 4.1.1 on 2023-01-12 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0016_alter_products_business_alter_promotion_business"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("buyer", "0005_merge_20221019_0956"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carts",
                to="seller.businessdetail",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carts",
                to="seller.products",
            ),
        ),
    ]
