# Generated by Django 4.1.1 on 2022-10-05 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_alter_businessdetail_phone_number_and_more'),
        ('order', '0003_remove_orderproduct_product_orderproduct_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='business',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_business', to='seller.businessdetail'),
        ),
    ]
