# Generated by Django 4.1.1 on 2022-10-16 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0005_seller_alter_products_options_and_more"),
        ("order", "0006_order_business"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="business",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders_business",
                to="seller.businessdetail",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="amount",
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="business",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_business",
                to="seller.businessdetail",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="product",
            field=models.ForeignKey(
                default=10,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="list_of_order_products",
                to="seller.products",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="quantity",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
