# Generated by Django 4.1.1 on 2022-10-19 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_business_alter_order_total_amount_and_more'),
        ('order', '0007_alter_order_updated_by_alter_orderdetail_updated_by_and_more'),
    ]

    operations = [
    ]
