# Generated by Django 4.1.2 on 2022-11-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0008_merge_20221019_0956"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderproduct",
            name="lmitate",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
