# Generated by Django 4.1.1 on 2023-02-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0010_alter_order_business_alter_order_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Placed", "Placed"),
                    ("Processing", "Processing"),
                    ("Shipped", "Shipped"),
                    ("Cancel", "Cancel"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderdetail",
            name="status",
            field=models.CharField(
                choices=[
                    ("Placed", "Placed"),
                    ("Processing", "Processing"),
                    ("Shipped", "Shipped"),
                    ("Cancel", "Cancel"),
                ],
                max_length=20,
            ),
        ),
    ]
