# Generated by Django 4.1.1 on 2023-03-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0011_alter_order_status_alter_orderdetail_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="note",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
