# Generated by Django 4.1.1 on 2023-03-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0012_order_note"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="note",
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="note",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
