# Generated by Django 4.1.1 on 2023-03-14 11:37

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0013_remove_order_note_orderproduct_note"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderproduct",
            name="note",
        ),
        migrations.AddField(
            model_name="order",
            name="note",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
